### ISSUE TITLE
[Meta] Update integTest gradle scripts to run via remote cluster independently

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-plugins#103]
**Is your feature request related to a problem?**
With the existing implementation of integration tests, opensearch plugins use the same test framework as local integration tests which spin up test clusters by itself. This is a hacky way to override the endpoint from local spun up test clusters (via `opensearch.testclusters` gradle plugin) with the remote cluster endpoint. 

The solution doesn't work when we would like to test the opensearch bundle as part of the release. The test frameworks expect the artifact to be available before we could test them. To clean this up, plugins have to create gradle scripts for remote endpoints to run https://github.com/opensearch-project/opensearch-build#integration-tests for the release cycle. 

**What solution would you like?**
Refer to: https://github.com/opensearch-project/anomaly-detection/pull/298 and make similar changes to the plugin.
Also if you have a custom name to invoke these tests, update the `integtest.sh` script in https://github.com/opensearch-project/opensearch-build/blob/main/scripts/default/integtest.sh 

- [x] https://github.com/opensearch-project/alerting/issues/237
- [x] https://github.com/opensearch-project/anomaly-detection/issues/315
- [x] https://github.com/opensearch-project/asynchronous-search/issues/63
- [x] https://github.com/opensearch-project/trace-analytics/issues/253
- [x] https://github.com/opensearch-project/dashboards-reports/issues/225
- [x] https://github.com/opensearch-project/dashboards-visualizations/issues/39
- [x] https://github.com/opensearch-project/index-management/issues/192
- [x] https://github.com/opensearch-project/job-scheduler/issues/98
- [x] https://github.com/opensearch-project/k-NN/issues/198
- [x] https://github.com/opensearch-project/performance-analyzer/issues/89
- [x] https://github.com/opensearch-project/security-dashboards-plugin/issues/858
- [x] https://github.com/opensearch-project/security/issues/1499
- [x] https://github.com/opensearch-project/sql/issues/281
- [x] https://github.com/opensearch-project/trace-analytics/issues/223
- [x] https://github.com/opensearch-project/cross-cluster-replication/issues/244

**Comment by ankitkala** [comment]
@saratvemulapalli FYI: For replication plugin, we'd need at least 2 clusters to test the replication use cases. Please make sure that this the integ test creates more than one domain.

**Comment by saratvemulapalli** [comment]
@ankitkala thanks a great point. How does replication plugin run integration tests against external clusters?

**Comment by cliu123** [comment]
@saratvemulapalli Does this apply to frontend plugins? I see security-dashboards-plugin is included here.

**Comment by saratvemulapalli** [comment]
@cliu123 it doesn't. We create issues using [meta](https://github.com/opensearch-project/opensearch-plugins/blob/main/plugins/.meta).

Looks like dashboards security was incorrectly categorized and was fixed in https://github.com/opensearch-project/opensearch-plugins/pull/114.
Feel free to close the issue.

**Comment by dblock** [comment]
I've re-labeled this 2.0 so we don't lose it. @saratvemulapalli Care to followup?
