### ISSUE TITLE
[Meta] Ensure plugins work with Dashboards Node v14.18.2

### ISSUE THREAD

**Issue by boktorbb-amzn** [opensearch-project/opensearch-plugins#118]
Dashboards has upgraded Node to v14.18.2 and this is for plugin teams to verify that their plugins work with the new version upgrade. The Dashboards branch running the upgraded node is [main](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main).

Here is the parent Node 14 upgrade issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/920

A list of things to check is:
* Your plugin's node version is bumped to 14.18.2
* Your plugin's `@types/node` package is bumped to `^14.17.32` if it's used
* Plugin builds and runs on Dashboards
* All of your plugin's tests pass
* Your GitHub workflows are not broken by the node version change and updated if they do
* Any sanity/smoke testing is successful

- [x] https://github.com/opensearch-project/observability/issues/353
- [x] https://github.com/opensearch-project/alerting-dashboards-plugin/issues/161
- [x] https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/164
- [x] https://github.com/opensearch-project/index-management-dashboards-plugin/issues/137
- [x] https://github.com/opensearch-project/notifications/issues/371
- [x] https://github.com/opensearch-project/dashboards-reports/issues/260
- [x] https://github.com/opensearch-project/sql/issues/343
- [x] https://github.com/opensearch-project/security-dashboards-plugin/issues/875

**Comment by dblock** [comment]
Did you mean this to be a parent issue and open one in each plugin?

**Comment by boktorbb-amzn** [comment]
> Did you mean this to be a parent issue and open one in each plugin?
I meant for each plugin team to verify their plugin against our Node 14 branch in case I missed anything in my own investigation. I’m not sure if I was supposed to open just a parent issue here or one in each Dashboards plugin repo.

**Comment by dblock** [comment]
> > Did you mean this to be a parent issue and open one in each plugin?
> 
> I meant for each plugin team to verify their plugin against our Node 14 branch in case I missed anything in my own investigation. I’m not sure if I was supposed to open just a parent issue here or one in each Dashboards plugin repo.

Make this a parent issue and open an issue in every plugin using meta. It should look like [this](https://github.com/opensearch-project/opensearch-plugins/issues/107) for example.

**Comment by dblock** [comment]
@boktorbb-amzn What shall we do about this?

**Comment by boktorbb-amzn** [comment]
> @boktorbb-amzn What shall we do about this?

As long as all plugins are building against Dashboards 2.0 successfully then we can close the issue
