### ISSUE TITLE
Support rolling upgrades for OpenSearch plugins, and restart upgrades for OpenSearch Dashboards Plugins 1.0

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-plugins#12]
Coming from https://github.com/opensearch-project/OpenSearch/issues/671. Plugins are upgraded to OpenSearch, while supporting backward compatibility. We need design and documentation for the following.

- [x] Renaming Namespaces `com.amazon.opendistroforelasticsearch` to `org.opensearch`
- [x] Renaming Classes, Methods, Variables 
- [x] Renaming Remaining Identifiers (e.g. `Opendistro` to `OpenSearch`).
- [x] Renaming, and Backwards Compatibility for Rest APIs
- [x] Renaming, and Backwards Compatibility for Settings 
- [x] Renaming, and Backwards Compatibility for Indices
- [ ] Run in a backwards compatible way on top of OpenSearch 1.0 that has joined an ES 7.10.x cluster 
- [ ] Run in a backwards compatible way on top of OpenSearch 1.0 that has joined an ODFE 1.13.x cluster 
- [ ] Rolling upgrades for the Opendistro version 1.13 of the plugin

**Comment by dblock** [comment]
Settings renaming support in progress in https://github.com/opensearch-project/OpenSearch/pull/643.

**Comment by dblock** [comment]
API endpoints discussion in https://github.com/opensearch-project/opensearch-plugins/issues/13

**Comment by cliu123** [comment]
> Settings: #15 (example: [opensearch-project/job-scheduler#20](https://github.com/opensearch-project/job-scheduler/pull/20)).

@dblock This looks great! Looking forward to a POC for migratin indices.

**Comment by dblock** [comment]
I opened https://github.com/opensearch-project/opensearch-plugins/issues/17 to track indices, @saratvemulapalli is looking into that.

**Comment by saratvemulapalli** [comment]
APIs: Take a look at https://github.com/opensearch-project/anomaly-detection/pull/35
Let me know if you have any concerns.

**Comment by cliu123** [comment]
@dblock @saratvemulapalli 
I see that `Renaming Namespaces` has been checked. Have we already had a decision/POC for it? 
How does renaming all class names and namespaces support backward compatibility, e.g Java serialization, Transport Actions? Especially during B/G deployment on the managed service where nodes are upgraded/migrated from `opendistro` cluster to `opensearch` cluster, how would `opensearch` cluster recognize the transport requests that have `opendistro` namespaces and classes serialized in the header and know how to deserialize them?

**Comment by dblock** [comment]
Renaming was focused on just the naming part. For the items you describe we already have some bugs open like https://github.com/opensearch-project/OpenSearch/issues/669 that @shwetathareja is looking into. If there's a scenario that you know of that is not covered, let's at least open an issue in OpenSearch?

**Comment by shwetathareja** [comment]
> @dblock @saratvemulapalli
> I see that `Renaming Namespaces` has been checked. Have we already had a decision/POC for it?
> How does renaming all class names and namespaces support backward compatibility, e.g Java serialization, Transport Actions? Especially during B/G deployment on the managed service where nodes are upgraded/migrated from `opendistro` cluster to `opensearch` cluster, how would `opensearch` cluster recognize the transport requests that have `opendistro` namespaces and classes serialized in the header and know how to deserialize them?

In general the Java Serialization and Transport action shouldn't fail during upgrade from Elasticsearch to OpenSearch as actual serialization and actions are not dependent on the class/ package names. As long the class attributes data types and their ordering in not changing while reading and write to stream, It should work as is. And as @dblock mentioned the version compatibility logic is already taken as part of https://github.com/opensearch-project/OpenSearch/pull/775

**Comment by dblock** [comment]
Are we ready to close this issue? What remains?

**Comment by saratvemulapalli** [comment]
> Are we ready to close this issue? What remains?

We should be able to close this as the follow up is: https://github.com/opensearch-project/opensearch-plugins/issues/39
