### ISSUE TITLE
Remove mappings types

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/opensearch-plugins#130]
As part of v2.0 release, mapping types are getting removed from OpenSearch engine. Below are the changes in the opensearch-engine. This is a meta issue for tracking the plugins side corresponding to mappings types removal from OpenSearch repository.

- Removal of type from rest end-points
- Removal of include_type_name parameter from API requests.

A high level changes are captured in gist below:
https://gist.github.com/dreamer-89/d76eaf639171e8ab32fa7f8b9d6c93d3

For more detailed changes, please check meta issue below:
Related: https://github.com/opensearch-project/opensearch/issues/1940

- [x] alerting-dashboards-plugin  https://github.com/opensearch-project/alerting-dashboards-plugin/issues/181
- [x] alerting https://github.com/opensearch-project/alerting/issues/317
- [x] anomaly-detection-dashboards-plugin:  https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/184
- [x] anomaly-detection https://github.com/opensearch-project/anomaly-detection/issues/394
- [x] asynchronous-search https://github.com/opensearch-project/asynchronous-search/issues/98
- [x] common-utils https://github.com/opensearch-project/common-utils/issues/123
- [x] dashboards-reports https://github.com/opensearch-project/dashboards-reports/issues/292
- [x] dashboards-visualizations https://github.com/opensearch-project/dashboards-visualizations/issues/52
- [x] index-management-dashboards-plugin https://github.com/opensearch-project/index-management-dashboards-plugin/issues/155
- [x] index-management https://github.com/opensearch-project/index-management/issues/282
- [x] job-scheduler https://github.com/opensearch-project/job-scheduler/issues/131
- [x] K-NN https://github.com/opensearch-project/k-NN/issues/303
- [x] notifications https://github.com/opensearch-project/notifications/issues/375
- [x] performance-analyzer https://github.com/opensearch-project/performance-analyzer/issues/145
- [x] performance-analyzer-rca https://github.com/opensearch-project/performance-analyzer-rca/issues/134
- [x] security-dashboards-plugin https://github.com/opensearch-project/security-dashboards-plugin/issues/914
- [x] security https://github.com/opensearch-project/security/issues/1658
- [x] sql https://github.com/opensearch-project/sql/issues/452
- [x] observability https://github.com/opensearch-project/observability/issues/523
- [x] cross-cluster-replication https://github.com/opensearch-project/cross-cluster-replication/issues/318
- [ ] opensearch-dashboards https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1290

**Comment by saratvemulapalli** [comment]
@dreamer-89 2.0 is out. Is there anything else remaining here?

**Comment by dreamer-89** [comment]
@saratvemulapalli : Thanks for checking on this. Yes, I think we can close this issue.
