### ISSUE TITLE
Standardize processes across all plugins

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-plugins#41]
Here is a meta issue for all plugins to track items which have to be taken care of between RC1 and GA for all the plugins.
Create an issue for the plugin you own and take care of the checklist.

- [ ] Plugin branching strategy - #35 
- [x] Backward compatibility testing - #39 
- [ ] DCO checks - https://github.com/opensearch-project/opensearch-build/issues/53
- [x] Broken links check - #29 
- [x] Standardize labels - #43 
- [ ] README.md, etc - https://github.com/opensearch-project/.github/issues/8
- [ ] #59
- [x] #58
- [x] #57
- [ ] Clean up branches  - https://github.com/opensearch-project/.github/issues/13
- [ ] Issue and PR templates - https://github.com/opensearch-project/.github/issues/9
- [x] #60
- [x] Plugins dependencies from Maven - #45 
- [x] Test coverage reporting - #46 
- [x] License header checks - #49 
- [x] Plugin artifact names - #47 
- [x] Branch protection rules - #52

**Comment by dblock** [comment]
I propose we split these into separate issues, and label them for v1.0.0? This way we can track a bunch of things under a label.  

Add consistent version labels.

**Comment by saratvemulapalli** [comment]
I understand the value of having multiple issues and can be tracked using a label. Would it be cumbersome for folks to track all the items needed?

**Comment by dblock** [comment]
> I understand the value of having multiple issues and can be tracked using a label. Would it be cumbersome for folks to track all the items to put thoughts into?

I do like having a meta issue, but an issue is an issue is an issue, we probably don't want to mix discussions and PRs

**Comment by ohltyler** [comment]
@saratvemulapalli @dblock another thing - now that Dashboards defaults to `kebab-case` for installed plugins, shall we finalize naming conventions for the build zips for Dashboards plugins? 

Current zip convention: `<pluginName>Dashboards-x.zip` (e.g., anomalyDetectionDashboards-1.0.0.0-rc1.zip`)

New ideas:
Option 1: identical to existing name, but in `kebab-case`: `<plugin-name>-dashboards-x.zip` (e.g., `anomaly-detection-dashboards-1.0.0.0-rc1.zip`.
Option 2: same convention as OpenSearch plugins, but replacing `opensearch` with `dashboards`: `dashboards-<plugin-name>-x.zip` (e.g., `dashboards-anomaly-detection-1.0.0.0-rc1.zip`.

Any thoughts here? I think either make sense. Option 1 will keep consistency with the existing plugin IDs which are following the camelcase convention of `<pluginNameDashboards>` (note that this could be changed, but will require more code changes & testing). Option 2 will keep consistency with OpenSearch plugin names, in regards to the zips at least.

**Comment by dblock** [comment]
@ohltyler I opened https://github.com/opensearch-project/opensearch-plugins/issues/47 (you can just open issues next time too!) will add comments there

**Comment by anirudha** [comment]
Looking ahead, I would like it if these issues with the broken down into individual issues. Individual issues so much easier to track￼

**Comment by dblock** [comment]
> Looking ahead, I would like it if these issues were broken down into individual issues. Individual issues so much easier to track￼

They are, aren't they?

**Comment by anirudha** [comment]
> > I understand the value of having multiple issues and can be tracked using a label. Would it be cumbersome for folks to track all the items to put thoughts into?
> 
> I do like having a meta issue, but an issue is an issue is an issue, we probably don't want to mix discussions and PRs
> 
> ... I don't feel strongly about any of this
we couldnt confirm if everything here was covered as separate issue. I saw a few. So now we had to see this meta issue plus a few others. 

No worries, will track only the issues in each repo. thanks!

**Comment by dblock** [comment]
I'm going to close this, we've done most of it, and original intent was just to collect work up to 1.0 GA.
