### ISSUE TITLE
Default CI Java Version to Java 11, run tests on 8, 11, 14 (and attempt 17)

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-plugins#64]
In the [documentation](https://github.com/opensearch-project/documentation-website/issues/75) we say:

> We recommend Java 11 (LTS), but OpenSearch also works with Java 8.

OpenSearch 1.0, 1.1 and 1.2 have used Java 14, which is [not an LTS release](https://blogs.oracle.com/javamagazine/post/java-long-term-support-lts). Because of this:

1. OpenSearch has lowered the JDK to 11 in https://github.com/opensearch-project/OpenSearch/pull/940 and version 1.3.0 will package JDK 11 as a runtime via https://github.com/opensearch-project/OpenSearch/pull/2301.
2. The build/distribution pipeline has lowered the JDK to 11 for 1.3.0 in https://github.com/opensearch-project/opensearch-build/pull/981. 

Plugins need to do the same for 1.3.0.

- Change the default Java version for CI in GitHub actions from 14/15 to 11 (LTS) and ensure 🟢 .
- Try adding Java 8, 14 (used before), and 17 (next LTS) to the CI matrix. 
  Open issues for any that don't work.
  e.g. https://github.com/opensearch-project/common-utils/pull/121
  e.g. https://github.com/opensearch-project/job-scheduler/pull/130
- Document Java versions in DEVELOPER_GUIDE.md for your project (copy/subset of [OpenSearch](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#install-prerequisites)).

Looking at 1.3.0:

- [bundled JDK = 11](https://github.com/opensearch-project/OpenSearch/blob/1.x/buildSrc/version.properties#L5)
- [build JDK = 11](https://github.com/opensearch-project/OpenSearch/blob/1.x/.ci/java-versions.properties#L16)
- [min JDK = 8](https://github.com/opensearch-project/OpenSearch/blob/1.x/.ci/java-versions.properties#L17)

Originally 1.3.0 was supposed to GA with JDK 17, but we ran  into a number of issues:
- https://github.com/opensearch-project/security/issues/1653
- https://github.com/opensearch-project/OpenSearch/issues/2298
- https://github.com/opensearch-project/OpenSearch/issues/2299
- https://github.com/opensearch-project/performance-analyzer/issues/144

For 2.0 we will remove support for Java 8, fix the above issues, upgrade to Gradle 7, and bundle JDK 17, which is https://github.com/opensearch-project/opensearch-plugins/issues/110.

### OpenSearch

- [x] opensearch-project/OpenSearch#2395
- [x] https://github.com/opensearch-project/common-utils/issues/100
       https://github.com/opensearch-project/common-utils/pull/121

### Plugins

- [x] https://github.com/opensearch-project/cross-cluster-replication/issues/254
- [x] https://github.com/opensearch-project/alerting/issues/242
- [x] https://github.com/opensearch-project/anomaly-detection/issues/320
- [x] https://github.com/opensearch-project/asynchronous-search/issues/66
- [x] https://github.com/opensearch-project/dashboards-reports/issues/230
- [x] https://github.com/opensearch-project/index-management/issues/200
- [x] https://github.com/opensearch-project/job-scheduler/issues/103
       https://github.com/opensearch-project/job-scheduler/pull/130
- [x] https://github.com/opensearch-project/k-NN/issues/220
- [x] https://github.com/opensearch-project/performance-analyzer/issues/91
- [x] https://github.com/opensearch-project/security-dashboards-plugin/issues/862
- [x] https://github.com/opensearch-project/security/issues/1502
- [x] https://github.com/opensearch-project/sql/issues/288
- [x] https://github.com/opensearch-project/trace-analytics/issues/260

### Related

- https://github.com/opensearch-project/opensearch-build/issues/74

**Comment by dblock** [comment]
@nknize Do you think this is reasonable in terms of asks? Should CI be using 8 instead of 11?
