### ISSUE TITLE
Add backwards compatibility tests for plugins

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-plugins#77]
https://opensearch.org/blog/technical-post/2021/11/bwc-testing-for-opensearch/
https://opensearch.org/blog/technical-posts/2021/06/opensearch-backwards-compatibility-faq/

This is a meta issue for tracking the plugins implementing the bwc tests:

- [x] anomaly-detection - https://github.com/opensearch-project/anomaly-detection/issues/188
- [x] security - https://github.com/opensearch-project/security/issues/1417
- [x] performance-analyzer - https://github.com/opensearch-project/performance-analyzer/issues/55
- [x] k-NN - https://github.com/opensearch-project/k-NN/issues/84
- [x] alerting - https://github.com/opensearch-project/alerting/issues/147
- [ ] job-scheduler - https://github.com/opensearch-project/job-scheduler/issues/53
- [x] asynchronous-search - https://github.com/opensearch-project/asynchronous-search/issues/33
- [x] index-management - https://github.com/opensearch-project/index-management/issues/125
- [x] sql - https://github.com/opensearch-project/sql/issues/193
- [x] performance-analyzer-rca - https://github.com/opensearch-project/performance-analyzer-rca/issues/59
- [x] cross-cluster-replication - https://github.com/opensearch-project/cross-cluster-replication/issues/116
- [x] data-prepper - https://github.com/opensearch-project/data-prepper/issues/200
- [x] perftop - https://github.com/opensearch-project/perftop/issues/17
- [ ] geospatial - https://github.com/opensearch-project/geospatial/issues/5 
- [x] reports-scheduler - https://github.com/opensearch-project/dashboards-reports/issues/240
- [ ] notifications - https://github.com/opensearch-project/notifications/issues/301

**Comment by zhongnansu** [comment]
missing reports-scheduler plugin?
https://github.com/opensearch-project/dashboards-reports/tree/main/reports-scheduler
