### ISSUE TITLE
Update plugin description blurbs

### ISSUE THREAD

**Issue by jcgraybill** [opensearch-project/opensearch-plugins#92]
Placeholder meta-issue for a campaign that will be part of OpenSearch 1.2. Each plugin has a short descriptive text blurb that says what it does: this appears in plugin-descriptor.properties (OpenSearch plugins) or package.json (OpenSearch Dashboards plugins), as well as on [the project website's "source" page](https://opensearch.org/source.html) and in the "About" section of every repo. These were created one-by-one over the years as plugins were created, so looking at them all together now it would be hard for somebody new to the project to use these to understand what the plugins do. 

PRs with new text [TK](https://en.wikipedia.org/wiki/To_come_(publishing)), will be linked to this meta-issue.

- [x] https://github.com/opensearch-project/alerting-dashboards-plugin/issues/132
- [x] https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/102
- [x] https://github.com/opensearch-project/alerting/issues/206
- [x] https://github.com/opensearch-project/anomaly-detection/issues/267
- [x] https://github.com/opensearch-project/asynchronous-search/issues/50
- [x] https://github.com/opensearch-project/dashboards-notebooks/issues/90
- [x] https://github.com/opensearch-project/dashboards-reports/issues/181
- [x] https://github.com/opensearch-project/dashboards-visualizations/issues/32
- [x] https://github.com/opensearch-project/index-management-dashboards-plugin/issues/108
- [x] https://github.com/opensearch-project/index-management/issues/169
- [x] https://github.com/opensearch-project/job-scheduler/issues/73
- [x] https://github.com/opensearch-project/k-NN/issues/137
- [x] https://github.com/opensearch-project/notifications/issues/347
- [x] https://github.com/opensearch-project/performance-analyzer/issues/72
- [x] https://github.com/opensearch-project/security-dashboards-plugin/issues/837
- [x] https://github.com/opensearch-project/security/issues/1467
- [x] https://github.com/opensearch-project/sql/issues/232
- [x] https://github.com/opensearch-project/trace-analytics/issues/134

**Comment by CEHENKLE** [comment]
All updated :)
