### ISSUE TITLE
[META] Add Windows Support

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-plugins#95]
**Is your feature request related to a problem?**

Coming from https://github.com/opensearch-project/opensearch-build/issues/33. In order to release a Windows x64 distribution each plugin needs to work on Windows and include tools that are windows-specific as replacements for any bash scripts.

**What solution would you like?**

Every component has passing CI on Windows (`windows-latest` on GHA), including unit, integration and bcw tests, and has Windows-specific documentation, if needed.

- [ ] https://github.com/opensearch-project/OpenSearch/issues/1448
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2451
- [x] https://github.com/opensearch-project/alerting/issues/214
- [x] https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/104
- [x] https://github.com/opensearch-project/anomaly-detection/issues/274
- [x] https://github.com/opensearch-project/asynchronous-search/issues/51
- [x] https://github.com/opensearch-project/dashboards-notebooks/issues/91
- [x] https://github.com/opensearch-project/dashboards-reports/issues/191
- [x] https://github.com/opensearch-project/dashboards-visualizations/issues/33
- [ ] https://github.com/opensearch-project/index-management-dashboards-plugin/issues/114
- [x] https://github.com/opensearch-project/index-management/issues/172
- [x] https://github.com/opensearch-project/job-scheduler/issues/75
- [x] https://github.com/opensearch-project/k-NN/issues/157
- [x] https://github.com/opensearch-project/notifications/issues/358
- [ ] https://github.com/opensearch-project/performance-analyzer/issues/75
- [x] https://github.com/opensearch-project/security-dashboards-plugin/issues/845
- [x] https://github.com/opensearch-project/security/issues/1474
- [x] https://github.com/opensearch-project/sql/issues/249
- [x] https://github.com/opensearch-project/trace-analytics/issues/160
- [x] https://github.com/opensearch-project/cross-cluster-replication/issues/220
- [x] https://github.com/opensearch-project/ml-commons/issues/361
- [x] https://github.com/opensearch-project/geospatial/issues/158
- [x] https://github.com/opensearch-project/dashboards-maps/issues/55
- [x] https://github.com/opensearch-project/common-utils/issues/256
- [x] https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/33
- [x] https://github.com/opensearch-project/security-analytics/issues/86
- [x] https://github.com/opensearch-project/neural-search/issues/39
- [x] https://github.com/opensearch-project/dashboards-search-relevance/issues/16

Example PR: https://github.com/opensearch-project/index-management/pull/210

**Comment by dblock** [comment]
OpenSearch Windows CI: https://github.com/opensearch-project/OpenSearch/issues/1448
OpenSearch Dashboards Windows CI: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2451

**Comment by peterzhuamazon** [comment]
Add geospatial, dashboards-maps, common-utils:

- [ ] https://github.com/opensearch-project/geospatial/issues/158
- [ ] https://github.com/opensearch-project/dashboards-maps/issues/55
- [ ] https://github.com/opensearch-project/common-utils/issues/256

**Comment by derek-ho** [comment]
Hi all, I am trying to enable this for a few plugins (observability, sql, dashboards-reports, dashboards-visualizations), and am wondering if it makes sense to disable backward compatibility tests since this is the first release on windows/macos. 
Also seeing several errors like the following: 
`Could not HEAD 'https://artifacts.opensearch.org/releases/core/opensearch/1.1.0/opensearch-min-1.1.0-windows-x64.zip'. Received status code 403 from server: Forbidden`. Is this a known infra issue/will be resolved at some point? Thanks

**Comment by peterzhuamazon** [comment]
> Hi all, I am trying to enable this for a few plugins (observability, sql, dashboards-reports, dashboards-visualizations), and am wondering if it makes sense to disable backward compatibility tests since this is the first release on windows/macos. Also seeing several errors like the following for windows/macos CI: `Could not HEAD 'https://artifacts.opensearch.org/releases/core/opensearch/1.1.0/opensearch-min-1.1.0-windows-x64.zip'. Received status code 403 from server: Forbidden`. Is this a known infra issue/will be resolved at some point? Thanks

There is no 1.1.0 windows for sure because we havent release windows yet......
@CEHENKLE @bbarani wonder if we want to enable this once we have 1.x windows release later?

Thanks.

**Comment by heemin32** [comment]
Hi. I am facing an issue while building geospatial plugin in window. Do you have any idea what might have went wrong? The error only happens in main branch build. It works fine in 2.x branch. Thanks.
```
�  uncaught exception in thread [main]
�  java.lang.RuntimeException: can not run opensearch as root
�  	at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:124)
�  	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:191)
�  	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404)
�  	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180)
�  	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171)
�  	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
�  	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
�  	at org.opensearch.cli.Command.main(Command.java:101)
�  	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137)
�  	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103)
�  For complete error details, refer to the log at D:\a\geospatial\geospatial\build\testclusters\integTest-0\logs\integTest.log
```

**Comment by dblock** [comment]
I think we should manually publish an 2.3.0 Windows build that I know we were able to produce, to support bcw. If we ship 2.4.0 with Windows support and 2.5.0 fails to upgrade because of something in 2.4.0 it will be a lot more difficult to fix.

**Comment by bbarani** [comment]
@peterzhuamazon Can we publish the Windows artifacts in artifacts.opensearch.org as well?

**Comment by peterzhuamazon** [comment]
We already have 2.4.0 min in snapshots on artifacts, not 2.3.0 tho.

**Comment by peterzhuamazon** [comment]
My point being that are pointing to the wrong location, should be `snapshots` not `releases` or `release-candidates` anymore.

**Comment by dblock** [comment]
We found that a number of child issues were closed with only partial working CI (unit tests, but not integration tests). Those issues have been reopened and I updated the description here to reflect that we want 100% parity in tests across all supported platforms, linux and windows.
